const path = require('node:path')
const { createRequire } = require('node:module')
const fr = createRequire(path.join(__dirname, '..', 'frontend', 'package.json'))
const { chromium } = fr('playwright')
;(async () => {
  const b = await chromium.launch({ headless: true })
  const p = await b.newPage({ viewport: { width: 1600, height: 1000 } })
  p.on('console', m => console.log('[console]', m.type(), m.text().slice(0, 200)))
  p.on('pageerror', e => console.log('[pageerror]', e.message.split('\n')[0]))
  p.on('requestfailed', r => console.log('[reqfail]', r.url().slice(0, 120), r.failure()?.errorText))
  await p.goto('http://localhost:8090/', { waitUntil: 'load' })
  await p.waitForTimeout(5000)
  const html = await p.evaluate(() => document.body.innerHTML.slice(0, 300))
  console.log('BODY:', html)
  await b.close()
})()
